function [simscores1] = genSimscores(path)
curDir = pwd;
cd(path);
simscores = cell(3,3);
try
    load('distmahalicosCam1toCam1.mat');
    simscores{1,1} = distmahalicos12;
    load('distmahalicosCam1toCam2.mat');
    simscores{1,2} = distmahalicos12;
    simscores{2,1} = distmahalicos12';
    load('distmahalicosCam1toCam3.mat');
    simscores{1,3} = distmahalicos12;
    simscores{3,1} = distmahalicos12';
    load('distmahalicosCam2toCam2.mat');
    simscores{2,2} = distmahalicos12;
    load('distmahalicosCam2toCam3.mat');
    simscores{2,3} = distmahalicos12;
    simscores{3,2} = distmahalicos12';
    load('distmahalicosCam3toCam3.mat');
    simscores{3,3} = distmahalicos12;
catch
    load('disteudCam1toCam1.mat');
    simscores{1,1} = disteud12;
    load('disteudCam1toCam2.mat');
    simscores{1,2} = disteud12;
    simscores{2,1} = disteud12';
    load('disteudCam1toCam3.mat');
    simscores{1,3} = disteud12;
    simscores{3,1} = disteud12';
    load('disteudCam2toCam2.mat');
    simscores{2,2} = disteud12;
    load('disteudCam2toCam3.mat');
    simscores{2,3} = disteud12;
    simscores{3,2} = disteud12';
    load('disteudCam3toCam3.mat');
    simscores{3,3} = disteud12;
end;

norm = [1:2:27];
ret = [2:2:28];
simscores1 = cell(6,6);
simscores1{1,2} = simscores{1,2}(norm,norm);
simscores1{1,3} = simscores{1,3}(norm,norm);
simscores1{1,4} = simscores{1,1}(norm,ret);
simscores1{1,5} = simscores{1,2}(norm,ret);
simscores1{1,6} = simscores{1,3}(norm,ret);
simscores1{2,1} = simscores{2,1}(norm,norm);
simscores1{2,3} = simscores{2,3}(norm,norm);
simscores1{2,4} = simscores{2,1}(norm,ret);
simscores1{2,5} = simscores{2,2}(norm,ret);
simscores1{2,6} = simscores{2,3}(norm,ret);
simscores1{3,1} = simscores{3,1}(norm,norm);
simscores1{3,2} = simscores{3,2}(norm,norm);
simscores1{3,4} = simscores{3,1}(norm,ret);
simscores1{3,5} = simscores{3,2}(norm,ret);
simscores1{3,6} = simscores{3,3}(norm,ret);
simscores1{4,1} = simscores{1,1}(ret,norm);
simscores1{4,2} = simscores{1,2}(ret,norm);
simscores1{4,3} = simscores{1,3}(ret,norm);
simscores1{4,5} = simscores{1,2}(ret,ret);
simscores1{4,6} = simscores{1,3}(ret,ret);
simscores1{5,1} = simscores{2,1}(ret,norm);
simscores1{5,2} = simscores{2,2}(ret,norm);
simscores1{5,3} = simscores{2,3}(ret,norm);
simscores1{5,4} = simscores{2,1}(ret,ret);
simscores1{5,6} = simscores{2,3}(ret,ret);
simscores1{6,1} = simscores{3,1}(ret,norm);
simscores1{6,2} = simscores{3,2}(ret,norm);
simscores1{6,3} = simscores{3,3}(ret,norm);
simscores1{6,4} = simscores{3,1}(ret,ret);
simscores1{6,5} = simscores{3,2}(ret,ret);
cd(curDir);
return;